// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrseijpesnmztuugmsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cnNlaWpwZXNubXp0dXVnbXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzkwMTEsImV4cCI6MjA3MzQ1NTAxMX0.Nr7RteC_RzAMUNO_ejem0V1_GBQk-weQ9ZI12CRffzQ";

// Schema version for cache busting - increment when schema changes
const SCHEMA_VERSION = '2.4';

// Clear Supabase schema cache if version changed
const cachedVersion = localStorage.getItem('supabase_schema_version');
if (cachedVersion !== SCHEMA_VERSION) {
  console.log('Schema version changed from', cachedVersion, 'to', SCHEMA_VERSION);
  console.log('Clearing all Supabase cache...');
  // Clear all Supabase-related localStorage items
  Object.keys(localStorage).forEach(key => {
    if (key.startsWith('sb-') || key.includes('supabase')) {
      console.log('Removing:', key);
      localStorage.removeItem(key);
    }
  });
  localStorage.setItem('supabase_schema_version', SCHEMA_VERSION);
  console.log('Supabase cache cleared. Reloading page...');
  // Force a hard reload to ensure fresh state
  setTimeout(() => window.location.reload(), 100);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input: RequestInfo | URL, init?: RequestInit) => fetch(input, init)
  },
  db: {
    schema: 'public'
  }
});