// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrseijpesnmztuugmsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cnNlaWpwZXNubXp0dXVnbXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzkwMTEsImV4cCI6MjA3MzQ1NTAxMX0.Nr7RteC_RzAMUNO_ejem0V1_GBQk-weQ9ZI12CRffzQ";

// Schema version for cache busting - increment when schema changes
const SCHEMA_VERSION = '2.5';

// Clear Supabase schema cache if version changed
const cachedVersion = localStorage.getItem('supabase_schema_version');
if (cachedVersion !== SCHEMA_VERSION) {
  console.log('🔄 Schema version changed from', cachedVersion, 'to', SCHEMA_VERSION);
  console.log('🗑️ Clearing Supabase schema cache...');
  
  // Clear all localStorage EXCEPT auth tokens
  Object.keys(localStorage).forEach(key => {
    // Keep auth tokens (sb-*-auth-*) and the version key
    if (key.includes('auth') || key === 'supabase_schema_version') {
      return;
    }
    console.log('Removing cache:', key);
    localStorage.removeItem(key);
  });
  
  // Clear ALL sessionStorage (safe to clear)
  sessionStorage.clear();
  
  // Set new version
  localStorage.setItem('supabase_schema_version', SCHEMA_VERSION);
  
  console.log('✅ Cache cleared. Reloading page...');
  
  // Force immediate hard reload
  window.location.reload();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input: RequestInfo | URL, init?: RequestInit) => fetch(input, init)
  },
  db: {
    schema: 'public'
  }
});